# Generated by Django 4.2.6 on 2024-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="obj_det",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用户")),
                (
                    "img",
                    models.FileField(
                        max_length=128, upload_to="obj_dect/", verbose_name="Logo"
                    ),
                ),
            ],
        ),
    ]
